[build]
#  publish = "exampleSite/public"
#  command = "cd exampleSite && hugo --gc --themesDir ../.."
  publish = "public"
  command = "hugo --gc"

[build.environment]
  HUGO_VERSION = "0.95.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
